#### Spatial base layer ####
# Protection scenarios (Figure 1)
print("Now calculating: Protection scenarios")

# MPA size frequency obtained from WDPA database downloaded from http://www.protectedplanet.net/search?marine=1 in March 2015
# calculations of MPA size frequency are done in MPA_size.org
MPA_size_dist_coast <- read.csv("MPA_size_dist_coast.csv")
MPA_size_dist_mar <- read.csv("MPA_size_dist_mar.csv")

#### load pre-existing MPAs ####
require(rgdal)
MPAs_coast <- readOGR(dsn=getwd(),layer="MPAs_coast")
MPAs_mar <- readOGR(dsn=getwd(),layer="MPAs_mar")
EEZ <- readOGR(dsn=getwd(),layer="eez_iho_union_v2")

# remove Canadian part of the Davis Strait for EEZ
EEZ <- EEZ[EEZ$marregion!="Canadian part of the Davis Strait",]

# standard projection
require(sp)
MPAs_coast <- spTransform(MPAs_coast,CRS(proj))
MPAs_mar <- spTransform(MPAs_mar,CRS(proj))
EEZ <- spTransform(EEZ,CRS(proj))
EEZ <- unionSpatialPolygons(EEZ,rep(1,length(EEZ)))

#### load DFO Area of Interest ####
# shapefile generated by georeferencing map images
# Maps downloaded from http://www.dfo-mpo.gc.ca/oceans/marineareas-zonesmarines/mpa-zpm/index-eng.htm
MPAs_AOI <- readOGR(dsn=getwd(),layer="DFO_AreaOfInterest")
MPAs_AOI <- spTransform(MPAs_AOI,CRS(proj))

#### plot MPAs ####
require(rgeos)
plot(EEZ)
plot(MPAs_coast,add=T,col='blue')
plot(MPAs_mar,add=T,col='red')
plot(MPAs_AOI,add=T,col='green')

#### unique IDs ####
MPAs_AOI <- spChFIDs(MPAs_AOI,paste("AOI",c(1:length(MPAs_AOI))))
MPAs_coast <- spChFIDs(MPAs_coast,paste("coast",c(1:length(MPAs_coast))))
MPAs_mar <- spChFIDs(MPAs_mar,paste("mar",c(1:length(MPAs_mar))))

#### rbind MPAs ####
MPAs <- rbind(MPAs_AOI,MPAs_coast)
MPAs <- rbind(MPAs,MPAs_mar)

# remove Canadian part of the Davis Strait for MPA
MPAs <- MPAs[as.logical(gContains(EEZ,MPAs,byid=T)),]

#### ignore any MPAs smaller than 10% of grid size ####
MPAs <- MPAs[gArea(MPAs,byid=T)/(10^6)>(0.1*(cell_size^2)),]

#### match dataframe for p ####
df <- MPAs@data[1,]
df[,sapply(df, is.numeric)] <- 0
df[,sapply(df, is.numeric)==F] <- NA
df <- df[rep(1,length(p)),]
p <- SpatialPolygonsDataFrame(p,df,match.ID = F)
p <- spChFIDs(p,paste("p",c(1:length(p))))

#### make Canada (land) polygon for placement of coastal MPAs ####
data(wrld_simpl)
Canada <- wrld_simpl[wrld_simpl$NAME=="Canada", ]
Canada <- spTransform(Canada,CRS(proj))
rm(wrld_simpl)
plot(Canada)

coastal <- as.vector(gDistance(p,Canada,byid=T)<cell_size)
plot(p[coastal,])

# #### place coastal MPAs ####
# print("Establishing new coastal randomly placed MPAs")
# MPAs_random <- generate_MPAs(MPAs,p[coastal,],p,MPA_coverage*CtoM,EEZ,"Random")
# plot(EEZ)
# plot(MPAs_random,col="blue",add=T)

print("Establishing new coastal maximum distance MPAs")
MPAs_maxdist <- generate_MPAs(MPAs,p[coastal,],p,MPA_coverage*CtoM,EEZ,"MaxDist")
plot(EEZ)
plot(MPAs_maxdist,col="blue",add=T)

print(paste0("Establishing new coastal fixed distance (",fixdist," km) MPAs"))
MPAs_fixed <- generate_MPAs(MPAs,p[coastal,],p,MPA_coverage*CtoM,EEZ,fixdist)
plot(EEZ)
plot(MPAs_fixed,col="blue",add=T)

# #### place marine MPAs ####
# print("Establishing new marine randomly placed MPAs")
# MPAs_random <- generate_MPAs(MPAs_random,p,p,(MPA_coverage-(MPA_coverage*CtoM)),EEZ,"Random")
# plot(EEZ)
# plot(MPAs_random,col="red",add=T)

print("Establishing new marine maximum distance MPAs")
MPAs_maxdist <- generate_MPAs(MPAs_maxdist,p,p,(MPA_coverage-(MPA_coverage*CtoM)),EEZ,"MaxDist")
plot(EEZ)
plot(MPAs_maxdist,col="red",add=T)

print(paste0("Establishing new marine fixed distance (",fixdist," km) MPAs"))
MPAs_fixed <- generate_MPAs(MPAs_fixed,p,p,(MPA_coverage-(MPA_coverage*CtoM)),EEZ,fixdist)
plot(EEZ)
plot(MPAs_fixed,col="red",add=T)

plot(EEZ)
plot(MPAs_maxdist,col="red",add=T)
