#### Spatial base layer ####
# Protection scenarios (Figure 1)
print("Now calculating: Protection scenarios")

# MPA size frequency obtained from WDPA database downloaded from http://www.protectedplanet.net/search?marine=1 in March 2015
# calculations of MPA size frequency are done in MPA_size.org
MPA_size_dist_coast <- read.csv("MPA_size_dist_coast.csv")
MPA_size_dist_mar <- read.csv("MPA_size_dist_mar.csv")

#### load pre-existing MPAs ####
require(rgdal)
MPAs_coast <- readOGR(dsn=getwd(),layer="MPAs_coast")
MPAs_mar <- readOGR(dsn=getwd(),layer="MPAs_mar")
EEZ <- readOGR(dsn=getwd(),layer="eez_iho_union_v2")
# standard projection
require(sp)
MPAs_coast <- spTransform(MPAs_coast,CRS(proj))
MPAs_mar <- spTransform(MPAs_mar,CRS(proj))
EEZ <- spTransform(EEZ,CRS(proj))

#### load DFO Area of Interest ####
# shapefile generated by georeferencing map images
# Maps downloaded from http://www.dfo-mpo.gc.ca/oceans/marineareas-zonesmarines/mpa-zpm/index-eng.htm
MPAs_AOI <- readOGR(dsn=getwd(),layer="DFO_AreaOfInterest")
MPAs_AOI <- spTransform(MPAs_AOI,CRS(proj))

#### plot MPAs ####
require(rgeos)
plot(EEZ)
plot(MPAs_coast,add=T,col='blue')
plot(MPAs_mar,add=T,col='red')
plot(MPAs_AOI,add=T,col='green')



sum(sapply(slot(p, "polygons"), slot, "area"))

