#### Spatial base layer ####
# Protection scenarios (Figure 1)
print("Now calculating: Protection scenarios")

# MPA size frequency obtained from WDPA database downloaded from http://www.protectedplanet.net/search?marine=1 in March 2015
# calculations of MPA size frequency are done in MPA_size.org
MPA_size_dist_coast <- read.csv("MPA_size_dist_coast.csv")
MPA_size_dist_mar <- read.csv("MPA_size_dist_mar.csv")

#### load pre-existing MPAs ####
require(rgdal)
MPAs_coast <- readOGR(dsn=getwd(),layer="MPAs_coast")
MPAs_mar <- readOGR(dsn=getwd(),layer="MPAs_mar")
EEZ <- readOGR(dsn=getwd(),layer="eez_iho_union_v2")
# standard projection
require(sp)
MPAs_coast <- spTransform(MPAs_coast,CRS(proj))
MPAs_mar <- spTransform(MPAs_mar,CRS(proj))
EEZ <- spTransform(EEZ,CRS(proj))
EEZ <- unionSpatialPolygons(EEZ,rep(1,length(EEZ)))

#### load DFO Area of Interest ####
# shapefile generated by georeferencing map images
# Maps downloaded from http://www.dfo-mpo.gc.ca/oceans/marineareas-zonesmarines/mpa-zpm/index-eng.htm
MPAs_AOI <- readOGR(dsn=getwd(),layer="DFO_AreaOfInterest")
MPAs_AOI <- spTransform(MPAs_AOI,CRS(proj))

#### plot MPAs ####
require(rgeos)
plot(EEZ)
plot(MPAs_coast,add=T,col='blue')
plot(MPAs_mar,add=T,col='red')
plot(MPAs_AOI,add=T,col='green')

#### unique IDs ####
MPAs_AOI <- spChFIDs(MPAs_AOI,paste("AOI",c(1:length(MPAs_AOI))))
MPAs_coast <- spChFIDs(MPAs_coast,paste("coast",c(1:length(MPAs_coast))))
MPAs_mar <- spChFIDs(MPAs_mar,paste("mar",c(1:length(MPAs_mar))))

#### make Canada (land) polygon for placement of coastal MPAs ####
data(wrld_simpl)
Canada <- wrld_simpl[wrld_simpl$NAME=="Canada", ]
Canada <- spTransform(Canada,CRS(proj))
rm(wrld_simpl)
plot(Canada)


coastal <- gDistance(p,Canada,byid=T)==0
plot(p[coastal])

sum(sapply(slot(p, "polygons"), slot, "area"))

size <- exp(generate_MPAs(1,MPA_size_dist_coast$cum_prob,MPA_size_dist_coast$breaks))
seed <- round(runif(1,1,length(p[coastal])))
gArea(p[coastal][seed])
gArea(EEZ)
